cosmetic: move shutdir functions to runtestsinshutdir

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -12,53 +12,6 @@ config_tail=10
 SHUT_PWD="$PWD"
 
 # -----------------------------------------------------------------------------
-rm_shutdir() {
-  if [ ! -e "$config_fullshutdir" ]; then
-    return
-  fi
-  if $config_keep; then
-    echo "name exists: $config_shutdir" >&3
-    echo "will not overwrite" >&3
-    return 2
-  fi
-  if [ ! -d "$config_fullshutdir" ]; then
-    echo "is not shutdir: $config_shutdir" >&3
-    echo "will not overwrite" >&3
-    return 2
-  fi
-  rm -r -- "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error deleting $config_fullshutdir" >&3
-    echo "cannot continue" >&3
-    return 3
-  }
-}
-
-# -----------------------------------------------------------------------------
-mkdir_shutdir() {
-  mkdir -p -- "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error creating directory $config_fullshutdir" >&3
-    echo "cannot continue" >&3
-    return 3
-  }
-}
-
-cp_tests_shutdir() {
-  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error copying tests to $config_fullshutdir" >&3
-    echo "cannot continue" >&3
-    return 3
-  }
-}
-
-cd_shutdir() {
-  cd -- "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error changing directory to $config_fullshutdir" >&3
-    echo "cannot continue" >&3
-    return 3
-  }
-}
-
-# -----------------------------------------------------------------------------
 mkdir_logdir() {
   mkdir logdir > /dev/null 2>&1 || {
     echo "error creating logdir" >&3
@@ -291,6 +244,53 @@ runtestsandprintsummary() {
   runtestsinlogdir || return
   printsummary
   determineexitstatus
+}
+
+# -----------------------------------------------------------------------------
+rm_shutdir() {
+  if [ ! -e "$config_fullshutdir" ]; then
+    return
+  fi
+  if $config_keep; then
+    echo "name exists: $config_shutdir" >&3
+    echo "will not overwrite" >&3
+    return 2
+  fi
+  if [ ! -d "$config_fullshutdir" ]; then
+    echo "is not shutdir: $config_shutdir" >&3
+    echo "will not overwrite" >&3
+    return 2
+  fi
+  rm -r -- "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error deleting $config_fullshutdir" >&3
+    echo "cannot continue" >&3
+    return 3
+  }
+}
+
+# -----------------------------------------------------------------------------
+mkdir_shutdir() {
+  mkdir -p -- "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error creating directory $config_fullshutdir" >&3
+    echo "cannot continue" >&3
+    return 3
+  }
+}
+
+cp_tests_shutdir() {
+  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error copying tests to $config_fullshutdir" >&3
+    echo "cannot continue" >&3
+    return 3
+  }
+}
+
+cd_shutdir() {
+  cd -- "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error changing directory to $config_fullshutdir" >&3
+    echo "cannot continue" >&3
+    return 3
+  }
 }
 
 runtestsinshutdir() {
