cosmetic: rename to config_tempdir

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -317,21 +317,21 @@ collectnamesandwork() {
 }
 
 workintempdir() {
-  shuttempdir=$(mktemp -d --tmpdir shuttempdir.XXX 2> /dev/null) || {
+  config_tempdir=$(mktemp -d --tmpdir shuttempdir.XXX 2> /dev/null) || {
     echo "error creating tempdir" >&2
     echo "cannot continue" >&2
     return 3
   }
   (
-    cd "$shuttempdir" > /dev/null 2>&1 || {
-      echo "failed changing directory to $shuttempdir" >&2
+    cd "$config_tempdir" > /dev/null 2>&1 || {
+      echo "failed changing directory to $config_tempdir" >&2
       echo "cannot continue" >&2
       return 3
     }
     collectnamesandwork "$@"
   )
   exitstatus=$?
-  rm -rf "$shuttempdir" > /dev/null 2>&1 || {
+  rm -rf "$config_tempdir" > /dev/null 2>&1 || {
     echo "error deleting tempdir" >&2
     echo "not fatal but annoying" >&2
     return 3
