cosmetic: code order

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -63,6 +63,23 @@ setup() {
 }
 
 # -----------------------------------------------------------------------------
+mktemp_tempdir() {
+  config_tempdir="$(mktemp -d --tmpdir shuttempdir.XXX 2> /dev/null)" || {
+    echo "error creating tempdir" >&2
+    echo "cannot continue" >&2
+    return 3
+  }
+}
+
+cd_tempdir() {
+  cd -- "$config_tempdir" > /dev/null 2>&1 || {
+    echo "failed changing directory to $config_tempdir" >&2
+    echo "cannot continue" >&2
+    return 3
+  }
+}
+
+# -----------------------------------------------------------------------------
 collecttestnames() {
   # this function expects "$@" as argument
   # the same "$@" as the function configfromargv
@@ -82,23 +99,6 @@ collecttestnames() {
   done
   find "$SHUT_PWD" -type d -name "$config_shutdir" -prune -o \
         \( $print \) -printf "./%P\n" | sort
-}
-
-# -----------------------------------------------------------------------------
-mktemp_tempdir() {
-  config_tempdir="$(mktemp -d --tmpdir shuttempdir.XXX 2> /dev/null)" || {
-    echo "error creating tempdir" >&2
-    echo "cannot continue" >&2
-    return 3
-  }
-}
-
-cd_tempdir() {
-  cd -- "$config_tempdir" > /dev/null 2>&1 || {
-    echo "failed changing directory to $config_tempdir" >&2
-    echo "cannot continue" >&2
-    return 3
-  }
 }
 
 # -----------------------------------------------------------------------------
