cosmetic: move shutdir functions

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -103,6 +103,30 @@ deleteshutdir() {
   }
 }
 
+mkdir_shutdir() {
+  mkdir -p -- "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error creating directory $config_fullshutdir" >&2
+    echo "cannot continue" >&2
+    return 3
+  }
+}
+
+cp_tests_shutdir() {
+  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error copying tests to $config_fullshutdir" >&2
+    echo "cannot continue" >&2
+    return 3
+  }
+}
+
+cd_shutdir() {
+  cd -- "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error changing directory to $config_fullshutdir" >&2
+    echo "cannot continue" >&2
+    return 3
+  }
+}
+
 mkdir_logdir() {
   mkdir logdir > /dev/null 2>&1 || {
     echo "error creating logdir" >&2
@@ -322,30 +346,6 @@ runtestsandprintsummary() {
   }
   printsummary
   [ ! -s fail ] && [ ! -s error ] # exitstatus based on list empty or not
-}
-
-mkdir_shutdir() {
-  mkdir -p -- "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error creating directory $config_fullshutdir" >&2
-    echo "cannot continue" >&2
-    return 3
-  }
-}
-
-cp_tests_shutdir() {
-  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error copying tests to $config_fullshutdir" >&2
-    echo "cannot continue" >&2
-    return 3
-  }
-}
-
-cd_shutdir() {
-  cd -- "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error changing directory to $config_fullshutdir" >&2
-    echo "cannot continue" >&2
-    return 3
-  }
 }
 
 runtestsinshutdir() {
