cosmetic: move code

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -78,6 +78,22 @@ collecttestnames() {
   find "$SHUT_PWD" -type d -name "$config_shutdir" -prune -o \( $findargs \) -printf "./%P\n" | sort
 }
 
+deleteshutdir() {
+  if [ ! -e "$config_fullshutdir" ]; then
+    return
+  fi
+  if ! $config_delete && [ -d "$config_fullshutdir" ]; then
+    echo "name exists: $config_shutdir" >&2
+    echo "will not overwrite" >&2
+    return 2
+  fi
+  rm -rf "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error deleting $config_fullshutdir"
+    echo "cannot continue"
+    return 3
+  }
+}
+
 runtest() {
   testname=$1
   fulltestname=$(readlink -f "$SHUT_PWD/$testname")
@@ -238,22 +254,6 @@ runtestsinshutdir() {
     }
     runtestsandprintsummary
   )
-}
-
-deleteshutdir() {
-  if [ ! -e "$config_fullshutdir" ]; then
-    return
-  fi
-  if ! $config_delete && [ -d "$config_fullshutdir" ]; then
-    echo "name exists: $config_shutdir" >&2
-    echo "will not overwrite" >&2
-    return 2
-  fi
-  rm -rf "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error deleting $config_fullshutdir"
-    echo "cannot continue"
-    return 3
-  }
 }
 
 workisruntests() {
