cosmetic: move logdir functions

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -103,6 +103,20 @@ deleteshutdir() {
   }
 }
 
+mkdir_logdir() {
+  mkdir logdir > /dev/null 2>&1 || {
+    echo "error creating logdir" >&2
+    return 3
+  }
+}
+
+cd_logdir() {
+  cd logdir > /dev/null 2>&1 || {
+    echo "error changing directory to logdir" >&2
+    return 3
+  }
+}
+
 mkdir_testdir() {
   local testname="$1"
   mkdir -p -- "$testname" > /dev/null 2>&1 || {
@@ -262,20 +276,6 @@ runtests() {
   while read -r testname; do
     runtestandreporterror "$testname"
   done < ../tests
-}
-
-mkdir_logdir() {
-  mkdir logdir > /dev/null 2>&1 || {
-    echo "error creating logdir" >&2
-    return 3
-  }
-}
-
-cd_logdir() {
-  cd logdir > /dev/null 2>&1 || {
-    echo "error changing directory to logdir" >&2
-    return 3
-  }
 }
 
 runtestsinlogdir() {
