work catch error

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -451,7 +451,12 @@ workintempdir() {
 
 # -----------------------------------------------------------------------------
 workcatcherror() {
-  workintempdir "$@"
+  error=$(workintempdir "$@" 2>&1 1>&3) 3>&1
+  exitstatus=$?
+  if [ "$error" ]; then
+    echo "$error" >&2
+  fi
+  return "$exitstatus"
 }
 
 # -----------------------------------------------------------------------------
