workcatcherror after workintempdir

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -420,6 +420,16 @@ configthenwork() {
 }
 
 # -----------------------------------------------------------------------------
+workcatcherror() {
+  error=$(configthenwork "$@" 2>&1 1>&3) 3>&1
+  exitstatus=$?
+  if [ "$error" ]; then
+    echo "$error" >&2
+  fi
+  return "$exitstatus"
+}
+
+# -----------------------------------------------------------------------------
 rm_tempdir() {
   rm -r -- "$config_tempdir" > /dev/null 2>&1 || {
     echo "error deleting tempdir" >&2
@@ -433,7 +443,7 @@ workintempdir() {
   mktemp_tempdir || return
   (
     cd_tempdir || return
-    configthenwork "$@"
+    workcatcherror "$@"
   )
   local exitstatus=$?
   rm_tempdir || return
@@ -441,18 +451,8 @@ workintempdir() {
 }
 
 # -----------------------------------------------------------------------------
-workcatcherror() {
-  error=$(workintempdir "$@" 2>&1 1>&3) 3>&1
-  exitstatus=$?
-  if [ "$error" ]; then
-    echo "$error" >&2
-  fi
-  return "$exitstatus"
-}
-
-# -----------------------------------------------------------------------------
 main() {
-  workcatcherror "$@"
+  workintempdir "$@"
 }
 
 main "$@"
