cosmetic: move testdir functions to runtestintestdir

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -12,23 +12,6 @@ config_tail=10
 SHUT_PWD="$PWD"
 
 # -----------------------------------------------------------------------------
-mkdir_testdir() {
-  local testname="$1"
-  mkdir -p -- "$testname" > /dev/null 2>&1 || {
-    echo "error creating testdir" >&2
-    return 3
-  }
-}
-
-cd_testdir() {
-  local testname="$1"
-  cd -- "$testname" > /dev/null 2>&1 || {
-    echo "error changing directory to testdir" >&2
-    return 3
-  }
-}
-
-# -----------------------------------------------------------------------------
 mkdir_workdir() {
   mkdir workdir > /dev/null 2>&1 || {
     echo "error creating workdir" >&2
@@ -138,6 +121,23 @@ runtestandprintreport() {
   local fulltestname="$2"
   runtestinworkdir "$fulltestname" || return
   printreport "$testname"
+}
+
+# -----------------------------------------------------------------------------
+mkdir_testdir() {
+  local testname="$1"
+  mkdir -p -- "$testname" > /dev/null 2>&1 || {
+    echo "error creating testdir" >&2
+    return 3
+  }
+}
+
+cd_testdir() {
+  local testname="$1"
+  cd -- "$testname" > /dev/null 2>&1 || {
+    echo "error changing directory to testdir" >&2
+    return 3
+  }
 }
 
 # -----------------------------------------------------------------------------
