cosmetic: rename to testsfound

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -198,7 +198,7 @@ runtests() {
   local testname
   while read -r testname; do
     runtestcatchterror "$testname"
-  done < ../tests
+  done < ../testsfound
 }
 
 # -----------------------------------------------------------------------------
@@ -233,7 +233,7 @@ printlist() {
 }
 
 printcounts() {
-  wc -l tests pass fail error | {
+  wc -l testsfound pass fail error | {
     read -r runcount ignorefilename
     read -r passcount ignorefilename
     read -r failcount ignorefilename
@@ -296,8 +296,8 @@ mkdir_shutdir() {
 }
 
 cp_tests_shutdir() {
-  cp -- tests "$config_fullshutdir" > /dev/null 2>&1 || {
-    echo "error copying tests to $config_fullshutdir" >&3
+  cp -- testsfound "$config_fullshutdir" > /dev/null 2>&1 || {
+    echo "error copying testsfound to $config_fullshutdir" >&3
     echo "cannot continue" >&3
     return 3
   }
@@ -323,15 +323,15 @@ runtestsinshutdir() {
 
 # -----------------------------------------------------------------------------
 printtestnames() {
-  cat tests
-  local count=$(wc -l < tests)
+  cat testsfound
+  local count=$(wc -l < testsfound)
   echo "================"
   echo "would run: $count"
 }
 
 # -----------------------------------------------------------------------------
 workiftestsfound() {
-  [ -s tests ] || {
+  [ -s testsfound ] || {
     echo "no tests found"
     return 2
   }
@@ -355,7 +355,7 @@ collecttestnames() {
     fi
   done < patterns
   find "$SHUT_PWD" -type d -name "$config_shutdir" -prune -o \
-        \( $print \) -printf "./%P\n" | sort > tests
+        \( $print \) -printf "./%P\n" | sort > testsfound
 }
 
 collectnamesandwork() {
