cosmetic: move workdir functions

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -103,6 +103,20 @@ deleteshutdir() {
   }
 }
 
+mkdir_workdir() {
+  mkdir workdir > /dev/null 2>&1 || {
+    echo "error creating workdir" >&2
+    return 3
+  }
+}
+
+cd_workdir() {
+  cd workdir > /dev/null 2>&1 || {
+    echo "error changing directory to workdir" >&2
+    return 3
+  }
+}
+
 runtest() {
   local fulltestname="$1"
   (
@@ -128,20 +142,6 @@ runtestsaveoutputsplit() {
 runtestsaveoutputmerge() {
   local fulltestname="$1"
   runtestsaveexitstatus "$fulltestname" > ../output 3>&1
-}
-
-mkdir_workdir() {
-  mkdir workdir > /dev/null 2>&1 || {
-    echo "error creating workdir" >&2
-    return 3
-  }
-}
-
-cd_workdir() {
-  cd workdir > /dev/null 2>&1 || {
-    echo "error changing directory to workdir" >&2
-    return 3
-  }
 }
 
 runtestinworkdir() {
