test error mktemp

diff --git a/shut b/shut
--- a/shut
+++ b/shut
@@ -264,6 +264,8 @@ printtestnames() {
 
 doshut() {
   testnames=$(mktemp --tmpdir shuttestnames.XXX)
+  exitstatus=$?
+  if [ $exitstatus -eq 0 ]; then
   collecttestnames "$@" > "$testnames"
   if [ -s "$testnames" ]; then
     $shutaction_func "$testnames"
@@ -273,6 +275,11 @@ doshut() {
     exitstatus=3
   fi
   rm "$testnames"
+  else
+    echo "error creating tempfile" >&2
+    echo "cannot continue" >&2
+    exitstatus=2
+  fi
   return $exitstatus
 }
 
